### ISSUE TITLE
Documentation of commandline parameters

### ISSUE THREAD

**Issue by keram79** [SekoiaLab/Fastir_Collector#11]
It should be possible to set nearly every option that can be set in a profile on the commandline as well.
Unfortunately, there is nearly no documentation other than what the "-h" commandline parameter displays.
I would, for example, like to change the output format from json (default) to csv, but I couldn't find the right parameters to do so. 
Interestingly, executing .\fastir_x64.exe --output type=csv creates and output-folder named "type=csv", while the correct option to set the output-folder should be output_dir.

**Comment by keram79** [comment]
<pre>
D:\DEV\FastIR>FastIR_x64.exe --output type=csv

  ______        _   _____ _____
 |  ____|      | | |_   _|  __ \
 | |__ __ _ ___| |_  | | | |__) |
 |  __/ _` / __| __| | | |  _  /
 | | | (_| \__ \ |_ _| |_| | \ \
 |_|  \__,_|___/\__|_____|_|  \_\

     A forensic analysis tool
(( CTRL+C pressed ))
Traceback (most recent call last):
  File "<string>", line 410, in <module>
  File "<string>", line 359, in main
KeyboardInterrupt

D:\DEV\FastIR>dir
 [...]
20.10.2016  14:47    <DIR>          .
20.10.2016  14:47    <DIR>          ..
14.10.2016  17:29        14.285.416 FastIR_x64.exe
14.10.2016  17:45        13.875.512 FastIR_x86.exe
20.10.2016  14:36    <DIR>          list
20.10.2016  14:12    <DIR>          output
20.10.2016  14:47    <DIR>          type=csv
               2 Datei(en),     28.160.928 Bytes
               5 Verzeichnis(se), 77.496.827.904 Bytes frei

</pre>
