### ISSUE TITLE
Issue dump ram Windows XP

### ISSUE THREAD

**Issue by dubierthomas** [SekoiaLab/Fastir_Collector#15]
Error with dump ram on windows xp (32bits),

FastIR_x86.exe --packages dump --dump ram

FastIR.log
2016-12-06 13:14:47,885 - FastIR - ERROR - (3, 'StartService', "Le chemin d'acc\xe8s sp\xe9cifi\xe9 est introuvable."): will try to continue
2016-12-06 13:14:47,895 - FastIR - ERROR - Traceback (most recent call last):
  File "<string>", line 383, in main
  File "C:\CatchEvidence\build\pyinstaller\out00-PYZ.pyz\dump.dump", line 167, in csv_export_ram
  File "C:\CatchEvidence\build\pyinstaller\out00-PYZ.pyz\dump.dump", line 154, in _export_ram
error: (2, 'CreateFile', 'Le fichier sp\xe9cifi\xe9 est introuvable.')

2016-12-06 13:14:47,895 - FastIR - INFO - Check here E:\Tools\Collecte_PC3\output\2016-12-06_131445 for yours results

**Comment by sebdraven** [comment]
I have a question. FastIR is launched since a share ?

**Comment by dubierthomas** [comment]
Yes, FastIR with ram dump works if it is launched on main hard disk (C: )

**Comment by sebdraven** [comment]
It's a normal mechanism. When you make a dump ram, a service is created. It's the only solution to pass a userland context to kernel context. It's impossible to have a soft which create a service since a share.
