### ISSUE TITLE
FastIR_x64.exe - Windows2008R2 - Failed to execute script main - KeyError: u'custom_registry_keys'

### ISSUE THREAD

**Issue by AZobec** [SekoiaLab/Fastir_Collector#29]
During collection on Windows2008R2 system :
```
2018-11-06 11:23:46,410 - FastIR - INFO - Getting clipboard contents
2018-11-06 11:23:47,051 - FastIR - INFO - format 49161 DataObject
2018-11-06 11:23:47,051 - FastIR - INFO - format 49281 FileGroupDescriptorW
2018-11-06 11:23:47,051 - FastIR - INFO - format 49283 FileContents
2018-11-06 11:23:47,051 - FastIR - INFO - format 49332 Preferred DropEffect
2018-11-06 11:23:47,051 - FastIR - INFO - format 49171 Ole Private Data
Traceback (most recent call last):
  File "main.py", line 425, in <module>
  File "main.py", line 387, in main
  File "registry\windows2008ServerR2Users.py", line 7, in __init__
  File "registry\reg.py", line 279, in __init__
KeyError: u'custom_registry_keys'
Failed to execute script main
```

**Comment by SyBen** [comment]
Hello,

If you are not using the (default conf file)[https://github.com/SekoiaLab/Fastir_Collector/blob/master/FastIR.conf.sample], the field `custom_registry_keys` is mandatory. If you do not want to use this functionality you can set it to an empty string.
