### ISSUE TITLE
Error in windows Server VM

### ISSUE THREAD

**Issue by xaled** [SekoiaLab/Fastir_Collector#31]
Hello,

We've asked one of our constituencies to send us the output of FastIR Collector from a server. But, the program crashed with the following error:
```
Traceback (most recent call last):
  File "main.py", line 424, in <module>
  File "main.py", line 341, in set_options
  File "main.py", line 79, in set_environment_options
TypeError: cannot concatenate 'str' and 'NoneType' objects
Failed to execute script main
```
Unfortunately we do not have any details about the setup except that it's a VM running Windows Server 2016 Standard.

The error seems to be cause by the function `get_os_version()` returning None value in line 71 of `main.py`:
```python
    if operating_sys == settings.OS:
        release = get_os_version()
```

Thank you,

**Comment by EgeBalci** [comment]
I am getting the same exact error.
