### ISSUE TITLE
HOMEDRIVE environment variable does not exist in Windows 10

### ISSUE THREAD

**Issue by rootbsd** [SekoiaLab/Fastir_Collector#6]
The HOMEDRIVE Variable does not exist in Windows 10.

```
C:\Users\pouf\Downloads>FastIR_x64.exe --profile fastir.conf
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "C:\pylibs\pyinstaller-exedir\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\CatchEvidence\build\pyinstaller\out00-PYZ.pyz\factory.factory", line 3, in <module>
  File "C:\pylibs\pyinstaller-exedir\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\CatchEvidence\build\pyinstaller\out00-PYZ.pyz\settings", line 61, in <module>
  File "C:\CatchEvidence\build\pyinstaller\out00-PYZ.pyz\os", line 425, in __getitem__
KeyError: u'HOMEDRIVE'
```

**Comment by thansau239** [comment]
have the same issue

**Comment by na1984** [comment]
The same here, a couple of win10 machines without HOMEDRIVE :(.
Any hints for a rookie python programmer;)?

**Comment by DarkSurferZA** [comment]
Fix which can be added to the settings.py file on line 60. This happens when executing as a service or network account without a full environment variable stack. This fix will assume the default c:\ as the HOMEDRIVE. If OP could commit to master, you wont have to patch manually.

if 'HOMEDRIVE' not in os.environ:
	os.environ['HOMEDRIVE'} = 'c:\\'

**Comment by thansau239** [comment]
Thanks & Best Regards,
Trần Danh Nhân (Mr)
IT Security - Security Operation Center
TECHCOMBANK
Sent from my iPhone

On Dec 13, 2016, at 19:16, DarkSurferZA <notifications@github.com> wrote:

Fix which can be added to the settings.py file on line 60. This happens when executing as a service or network account without a full environment variable stack. This fix will assume the default c:\ as the HOMEDRIVE. If OP could commit to master, you wont have to patch manually.

if 'HOMEDRIVE' not in os.environ:
os.environ['HOMEDRIVE'} = 'c:\'

**Comment by dubierthomas** [comment]
Same issue in a cmd, run as administrator on Windows XP (32bits)
C:\Documents and Settings\TestFastIR\Mes documents\Collecte_PC3>FastIR_x86.exe
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "C:\pyinstaller-exedir\PyInstaller\loader\pyi_importers.py", line 270, in
 load_module
  File "C:\CatchEvidence\build\pyinstaller\out00-PYZ.pyz\factory.factory", line
3, in <module>
  File "C:\pyinstaller-exedir\PyInstaller\loader\pyi_importers.py", line 270, in
 load_module
  File "C:\CatchEvidence\build\pyinstaller\out00-PYZ.pyz\settings", line 61, in
<module>
  File "C:\CatchEvidence\build\pyinstaller\out00-PYZ.pyz\os", line 425, in __get
item__
KeyError: u'HOMEDRIVE'

**Comment by sebdraven** [comment]
Yep it's normal on Windows XP this env variable doesn't exist. So it's your profile file is not correctly configured
